FROM python:3.11.10
WORKDIR /app
COPY . /app
RUN apt update && pip install --upgrade pip
ENV LANG en_US.cp1252
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.cp1252
RUN apt update && apt install -y locales
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
CMD ["python", "app.py"]
